// CSCA Basics — Root knowledge map (最底层知识图谱)
// Each node is a foundational concept; its `links` extend to the rest of the app
// (kb = knowledge base topic, found = foundation lesson, sim = instrument simulator,
//  calc = mental-math drill, cn = academic Chinese level).
const ROOT_MAP = [
  {
    subj: "math", icon: "∑", color: "#002147", title: "数学 · 最底层知识", en: "Mathematics · The Foundational Floor",
    intro: "这些是你碰圆锥曲线、导数、向量之前必须先扎稳的地板。",
    introEn: "This is the floor you must stabilize before touching conic sections, derivatives, and vectors.",
    nodes: [
      { id: "r-math-realnum", icon: "ℝ", title: "实数与数轴", en: "Real numbers & number line",
        essence: "数系分类（有理 / 无理）、绝对值的几何意义、区间表示。集合与不等式都建在它上面。",
        essenceEn: "Number-system classification (rational / irrational), the geometric meaning of absolute value, interval notation. Sets and inequalities are built on it.",
        links: [ { type:"found", id:"fml-realnum", label:"地基 · 实数与数轴", labelEn:"Foundation · Real numbers & number line" }, { type:"kb", subj:"math", id:"math-sets", label:"知识库 · 集合", labelEn:"KB · Sets" } ] },
      { id: "r-math-algebra", icon: "∑", title: "代数式与运算", en: "Algebraic fluency",
        essence: "展开、因式分解、分式化简——CSCA 全程手算、禁用计算器。这是国际课程学生最容易塌的一层。",
        essenceEn: "Expansion, factoring, fraction simplification — CSCA is all by-hand, no calculator. This is the layer international-curriculum students most often collapse on.",
        links: [ { type:"found", id:"fml-algebra", label:"地基 · 代数式运算", labelEn:"Foundation · Algebraic operations" }, { type:"calc", id:"", label:"手算训练", labelEn:"Mental-math drill" } ] },
      { id: "r-math-coord", icon: "⊕", title: "平面直角坐标系", en: "Coordinate system",
        essence: "两点距离、中点、斜率、直线方程——解析几何（直线 / 圆 / 圆锥曲线）的总入口。",
        essenceEn: "Distance between two points, midpoint, slope, line equations — the master entry to analytic geometry (lines / circles / conics).",
        links: [ { type:"found", id:"fml-coord", label:"地基 · 坐标系", labelEn:"Foundation · Coordinate system" }, { type:"kb", subj:"math", id:"math-conics", label:"知识库 · 圆锥曲线", labelEn:"KB · Conic sections" } ] },
      { id: "r-math-func", icon: "ƒ", title: "函数概念", en: "Function basics",
        essence: "定义域 / 值域 / 单调性 / 奇偶性 / 图像。单调性、奇偶性是后续一切函数题的地基。",
        essenceEn: "Domain / range / monotonicity / parity / graph. Monotonicity and parity are the floor for all later function problems.",
        links: [ { type:"found", id:"fm-func", label:"地基 · 函数概念", labelEn:"Foundation · Function basics" }, { type:"kb", subj:"math", id:"math-func", label:"知识库 · 函数", labelEn:"KB · Functions" } ] },
      { id: "r-math-eq", icon: "≠", title: "方程与不等式", en: "Equations & inequalities",
        essence: "一元二次、分式、绝对值不等式是高频题；含参讨论是分水岭。",
        essenceEn: "Quadratic, fractional, and absolute-value inequalities are high-frequency; parameterized discussion is the dividing line.",
        links: [ { type:"found", id:"fm-eq", label:"地基 · 方程与不等式", labelEn:"Foundation · Equations & inequalities" }, { type:"kb", subj:"math", id:"math-inequalities", label:"知识库 · 不等式", labelEn:"KB · Inequalities" } ] },
      { id: "r-math-exp", icon: "a²", title: "指数与对数", en: "Exponents & logs",
        essence: "log 运算、换底公式、指数方程。CSCA 要求无计算器手算（记 lg2 / lg3 / lg7）。",
        essenceEn: "Log operations, change-of-base, exponential equations. CSCA requires calculator-free hand calculation (memorize lg2 / lg3 / lg7).",
        links: [ { type:"found", id:"fm-exp", label:"地基 · 指数对数", labelEn:"Foundation · Exponents & logs" }, { type:"kb", subj:"math", id:"math-elemfn", label:"知识库 · 初等函数", labelEn:"KB · Elementary functions" } ] },
      { id: "r-math-est", icon: "≈", title: "数与式估算", en: "Estimation",
        essence: "75 秒 / 题节奏下，估算比精确算更保命。所有国际课程学生都需「去计算器」再训练。",
        essenceEn: "At a 75-second-per-question pace, estimation saves more lives than exact calculation. All international-curriculum students need calculator-free re-training.",
        links: [ { type:"found", id:"fm-num", label:"地基 · 估算", labelEn:"Foundation · Estimation" }, { type:"calc", id:"", label:"手算训练", labelEn:"Mental-math drill" } ] }
    ]
  },
  {
    subj: "physics", icon: "atom", color: "#8b5cf6", title: "物理 · 最底层知识", en: "Physics · The Foundational Floor",
    intro: "单位、仪器、受力分析、图像法——中国物理的「招牌基本功」，国际课程往往缺。",
    introEn: "Units, instruments, force analysis, graph methods — the signature basics of Chinese physics, often missing from international curricula.",
    nodes: [
      { id: "r-phys-unit", icon: "kg", title: "单位与量纲", en: "Units & dimensions",
        essence: "SI 单位换算 + 量纲分析检验公式。CSCA 选择题常考，IB / AP 几乎不练。",
        essenceEn: "SI unit conversion + dimensional analysis to check formulas. Frequently tested in CSCA multiple-choice; rarely practiced in IB / AP.",
        links: [ { type:"found", id:"fp-unit", label:"地基 · 单位量纲", labelEn:"Foundation · Units & dimensions" }, { type:"kb", subj:"physics", id:"phys-measurement", label:"知识库 · 实验与测量", labelEn:"KB · Measurement & experiment" } ] },
      { id: "r-phys-instr", icon: "ruler", title: "仪器读数", en: "Instrument reading",
        essence: "游标卡尺、螺旋测微器、秒表、电表读数——「中国特色」必考，共同的盲区。",
        essenceEn: "Vernier caliper, micrometer, stopwatch, ammeter readings — a must-test 'Chinese characteristic', a common blind spot.",
        links: [ { type:"found", id:"fp-instrument", label:"地基 · 仪器读数", labelEn:"Foundation · Instrument reading" }, { type:"sim", id:"caliper", label:"模拟 · 游标卡尺", labelEn:"Sim · Caliper" }, { type:"sim", id:"micrometer", label:"模拟 · 千分尺", labelEn:"Sim · Micrometer" }, { type:"sim", id:"ammeter", label:"模拟 · 电流表", labelEn:"Sim · Ammeter" } ] },
      { id: "r-phys-kin", icon: "→", title: "运动学基础", en: "Kinematics",
        essence: "位移 / 速度 / 加速度定义 + 匀变速公式。力学与所有动力学的起点。",
        essenceEn: "Definitions of displacement / velocity / acceleration + uniformly accelerated motion formulas. The start of mechanics and all dynamics.",
        links: [ { type:"found", id:"fp-kinematics", label:"地基 · 运动学", labelEn:"Foundation · Kinematics" }, { type:"kb", subj:"physics", id:"phys-kinematics", label:"知识库 · 运动学", labelEn:"KB · Kinematics" } ] },
      { id: "r-phys-newton", icon: "F", title: "受力分析与牛顿定律", en: "Forces & Newton",
        essence: "画受力图 → 列 F=ma，是整块力学的地基。",
        essenceEn: "Draw the free-body diagram → write F=ma; the floor of the entire mechanics block.",
        links: [ { type:"found", id:"fp-newton", label:"地基 · 受力分析", labelEn:"Foundation · Force analysis" }, { type:"kb", subj:"physics", id:"phys-newton", label:"知识库 · 牛顿定律", labelEn:"KB · Newton's laws" } ] },
      { id: "r-phys-energy", icon: "W", title: "功与能", en: "Work & energy",
        essence: "W=Fs、动能定理、机械能守恒。能量观贯穿全部物理。",
        essenceEn: "W=Fs, work-energy theorem, conservation of mechanical energy. The energy view runs through all of physics.",
        links: [ { type:"found", id:"fp-energy", label:"地基 · 功与能", labelEn:"Foundation · Work & energy" }, { type:"kb", subj:"physics", id:"phys-energy", label:"知识库 · 功与能", labelEn:"KB · Work & energy" } ] },
      { id: "r-phys-graph", icon: "chartLine", title: "图像法", en: "Graph methods",
        essence: "v-t 图、F-x 图：斜率、面积代表的物理量——CSCA 高频。",
        essenceEn: "v-t and F-x graphs: the physical quantities represented by slope and area — high-frequency in CSCA.",
        links: [ { type:"found", id:"fp-graph", label:"地基 · 图像法", labelEn:"Foundation · Graph methods" }, { type:"kb", subj:"physics", id:"phys-kinematics", label:"知识库 · 运动学", labelEn:"KB · Kinematics" } ] },
      { id: "r-phys-vec", icon: "⟶", title: "矢量运算", en: "Vector algebra",
        essence: "力、速度、位移都是矢量；分量加减、点积必须手算。",
        essenceEn: "Force, velocity, displacement are all vectors; component addition/subtraction and dot product must be done by hand.",
        links: [ { type:"found", id:"fp-vector", label:"地基 · 矢量", labelEn:"Foundation · Vectors" }, { type:"kb", subj:"math", id:"math-vectors", label:"知识库 · 向量", labelEn:"KB · Vectors" } ] }
    ]
  },
  {
    subj: "chemistry", icon: "flask", color: "#10b981", title: "化学 · 最底层知识", en: "Chemistry · The Foundational Floor",
    intro: "原子、周期律、化学键、摩尔——化学计算的「通用货币」都从这里来。",
    introEn: "Atoms, periodicity, chemical bonds, moles — the 'common currency' of chemistry calculations all originates here.",
    nodes: [
      { id: "r-chem-atom", icon: "atom", title: "原子结构", en: "Atomic structure",
        essence: "核素符号 ᴬZX、质子 / 中子 / 电子数关系。后续结构理论的总根。",
        essenceEn: "Nuclide notation ᴬZX, the proton / neutron / electron count relationship. The root of all later structure theory.",
        links: [ { type:"found", id:"fc-atom", label:"地基 · 原子结构", labelEn:"Foundation · Atomic structure" }, { type:"kb", subj:"chemistry", id:"chem-atom", label:"知识库 · 原子结构", labelEn:"KB · Atomic structure" } ] },
      { id: "r-chem-periodic", icon: "table", title: "元素周期律", en: "Periodic law",
        essence: "周期表结构 + 半径 / 金属性 / 非金属性递变。无机化学的地图。",
        essenceEn: "Periodic table structure + trends in radius / metallic / non-metallic character. The map of inorganic chemistry.",
        links: [ { type:"found", id:"fc-periodic", label:"地基 · 周期律", labelEn:"Foundation · Periodic law" }, { type:"kb", subj:"chemistry", id:"chem-periodic", label:"知识库 · 周期律", labelEn:"KB · Periodic law" } ] },
      { id: "r-chem-bond", icon: "∞", title: "化学键与分子构型", en: "Chemical bonding",
        essence: "离子键 / 共价键 + VSEPR 判断构型。物质性质的解释器。",
        essenceEn: "Ionic / covalent bonds + VSEPR for geometry. The interpreter of substance properties.",
        links: [ { type:"found", id:"fc-bond", label:"地基 · 化学键", labelEn:"Foundation · Chemical bonding" }, { type:"kb", subj:"chemistry", id:"chem-bonding", label:"知识库 · 化学键", labelEn:"KB · Chemical bonding" } ] },
      { id: "r-chem-mole", icon: "n", title: "物质的量（摩尔）", en: "Mole concept",
        essence: "n=m/M=cV，化学计算的通用货币。所有计量题都从它出发。",
        essenceEn: "n=m/M=cV, the common currency of chemical calculation. All stoichiometry starts here.",
        links: [ { type:"found", id:"fc-mole", label:"地基 · 摩尔", labelEn:"Foundation · Mole concept" }, { type:"kb", subj:"chemistry", id:"chem-mole", label:"知识库 · 物质的量", labelEn:"KB · Mole concept" } ] },
      { id: "r-chem-bal", icon: "balance", title: "化学方程式配平", en: "Equation balancing",
        essence: "质量守恒；氧化还原用电子守恒法。写对方程是化学基本功。",
        essenceEn: "Mass conservation; redox via electron conservation. Writing correct equations is the basic skill of chemistry.",
        links: [ { type:"found", id:"fc-balance", label:"地基 · 配平", labelEn:"Foundation · Equation balancing" }, { type:"kb", subj:"chemistry", id:"chem-nomenclature", label:"知识库 · 化学用语", labelEn:"KB · Chemical notation" } ] },
      { id: "r-chem-ion", icon: "±", title: "离子反应", en: "Ionic reactions",
        essence: "离子方程式、沉淀 / 气体 / 水生成。离子共存题的核心。",
        essenceEn: "Ionic equations, precipitation / gas / water formation. The core of ion-coexistence problems.",
        links: [ { type:"found", id:"fc-equiv", label:"地基 · 离子反应", labelEn:"Foundation · Ionic reactions" }, { type:"kb", subj:"chemistry", id:"chem-reactions", label:"知识库 · 离子反应", labelEn:"KB · Ionic reactions" } ] },
      { id: "r-chem-redox", icon: "e⁻", title: "氧化还原反应", en: "Redox",
        essence: "氧化数、电子转移、配平。电化学与许多反应原理的底层。",
        essenceEn: "Oxidation number, electron transfer, balancing. The substrate of electrochemistry and many reaction principles.",
        links: [ { type:"found", id:"fc-redox", label:"地基 · 氧化还原", labelEn:"Foundation · Redox" }, { type:"kb", subj:"chemistry", id:"chem-redox", label:"知识库 · 氧化还原", labelEn:"KB · Redox" } ] }
    ]
  },
  {
    subj: "chinese", icon: "languages", color: "#f59e0b", title: "学术中文 · 最底层知识", en: "Academic Chinese · The Foundational Floor",
    intro: "中文授课方向必考。先攒术语，再读短文，最后上真实场景与模考。",
    introEn: "Required for Chinese-taught tracks. First build vocabulary, then read short texts, finally tackle real scenarios and the mock exam.",
    nodes: [
      { id: "r-cn-terms", icon: "book", title: "术语库", en: "Glossary (985 terms)",
        essence: "理科 + 文科 985 个核心术语。所有阅读与写作的词汇地基。",
        essenceEn: "985 core terms across science + liberal arts. The vocabulary floor for all reading and writing.",
        links: [ { type:"cn", id:"1", label:"L1 · 术语库", labelEn:"L1 · Glossary" } ] },
      { id: "r-cn-read", icon: "paragraph", title: "短篇学术阅读", en: "Short academic reading",
        essence: "学术文本阅读力。从术语过渡到成段理解的第一步。",
        essenceEn: "Academic-text reading ability. The first step from terms to paragraph-level comprehension.",
        links: [ { type:"cn", id:"2", label:"L2 · 短篇阅读", labelEn:"L2 · Short reading" } ] },
      { id: "r-cn-scene", icon: "news", title: "真实场景阅读", en: "Real-scenario reading",
        essence: "实验规程、仪器铭牌、SDS、新闻——考场真实材料的读法。",
        essenceEn: "Lab protocols, instrument nameplates, SDS, news — how to read real exam materials.",
        links: [ { type:"cn", id:"3", label:"L3 · 应用场景", labelEn:"L3 · Real scenarios" } ] },
      { id: "r-cn-mock", icon: "doc", title: "全真模考", en: "Full mock exam",
        essence: "80 题 90 分钟倒计时。把前面所有底层知识综合检验。",
        essenceEn: "80 questions, 90-minute countdown. A comprehensive test of all the foundational knowledge above.",
        links: [ { type:"cn", id:"4", label:"L4 · 80 题模考", labelEn:"L4 · 80-question mock" } ] }
    ]
  }
];
